### ISSUE TITLE
imageioAWT integration test fails with 22.3-dev

### ISSUE THREAD

**Issue by jerboaa** [Karm/mandrel-integration-tests#114]
Fails with:
```
[ERROR] Tests run: 11, Failures: 0, Errors: 1, Skipped: 4, Time elapsed: 448.609 s <<< FAILURE! - in org.graalvm.tests.integration.AppReproducersTest
[ERROR] imageioAWTTest{TestInfo}  Time elapsed: 89.856 s  <<< ERROR!
java.lang.UnsupportedOperationException
	at org.graalvm.tests.integration.AppReproducersTest.imageioAWT(AppReproducersTest.java:526)
	at org.graalvm.tests.integration.AppReproducersTest.imageioAWTTest(AppReproducersTest.java:417)
```

Also seen in CI here:
https://github.com/graalvm/mandrel/actions/runs/3127680442/jobs/5074987920#step:10:18615

**Comment by jerboaa** [comment]
Sigh, caused by #112 which adds an entry to the unmodifiable Set created by `Set.of`.

**Comment by jerboaa** [comment]
Interestingly we'd have seen this for the `libharfbuzz.a` case too. I guess we just didn't hit that JDK case for 11.
