### ISSUE TITLE
RuntimesSmokeTest.quarkusFullMicroProfile failing due to deprecated StackTrace option

### ISSUE THREAD

**Issue by jerboaa** [Karm/mandrel-integration-tests#167]
Mandrel IT test `RuntimesSmokeTest.quarkusFullMicroProfile` is failing because of the now deprecated `-H:+StackTrace` option. See this graal commit: https://github.com/oracle/graal/pull/6763/commits/c8a0e7654dcab6a51dd66b4922e3626ad81496a3 part of https://github.com/oracle/graal/pull/6763

The test fails with:
```
Error:  Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 522.484 s <<< FAILURE! - in org.graalvm.tests.integration.RuntimesSmokeTest
Error:  quarkusFullMicroProfile{TestInfo}  Time elapsed: 348.144 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: 
build-and-run.log log should not contain error or warning lines that are not whitelisted. See /home/runner/work/mandrel/mandrel/mandrel-integration-tests/testsuite/target/archived-logs/org.graalvm.tests.integration.RuntimesSmokeTest/quarkusFullMicroProfile/build-and-run.log and check these offending lines: 
Warning: Option 'StackTrace' is deprecated and might be removed in a future release. Please refer to the GraalVM release notes. ==> expected: <true> but was: <false>
	at org.graalvm.tests.integration.RuntimesSmokeTest.testRuntime(RuntimesSmokeTest.java:166)
	at org.graalvm.tests.integration.RuntimesSmokeTest.quarkusFullMicroProfile(RuntimesSmokeTest.java:194)
```
See https://github.com/graalvm/mandrel/actions/runs/5227497104/jobs/9439379129#step:11:13392

This affects the Windows mandrel IT run as well.

**Comment by jerboaa** [comment]
Stack traces are always turned on with 23.1, so we should just stop adding that option in quarkus.

**Comment by jerboaa** [comment]
Fixed on the quarkus side and we no longer see the issue. Example:
https://github.com/graalvm/mandrel/actions/runs/5295670650/jobs/9586499205#step:10:8738
