### ISSUE TITLE
[23.1] helidonQuickStart fails due to experimental options warning

### ISSUE THREAD

**Issue by jerboaa** [Karm/mandrel-integration-tests#189]
It fails with:

```
helidonQuickStart{TestInfo}  Time elapsed: 60.555 s  <<< FAILURE!
org.opentest4j.AssertionFailedError:
build-and-run.log log should not contain error or warning lines that are not whitelisted. See /disk/graal/upstream-sources/mandrel-integration-tests/testsuite/target/archived-logs/org.graalvm.tests.integration.RuntimesSmokeTest/helidonQuickStart/build-and-run.log and check these offending lines:
[INFO] Warning: The option '-H:IncludeResources=io/helidon/common/media/type/default-media-types.properties' is experimental and must be enabled via '-H:+UnlockExperimentalVMOptions' in the future.
[INFO] Warning: The option '-H:IncludeResources=META-INF/helidon/media-types.properties' is experimental and must be enabled via '-H:+UnlockExperimentalVMOptions' in the future.
[INFO] Warning: Please re-evaluate whether any experimental option is required, and either remove or unlock it. The build output lists all active experimental options, including where they come from and possible alternatives. If you think an experimental option should be considered as stable, please file an issue.
[INFO] Warning: The option '-H:Path=/disk/graal/upstream-sources/mandrel-integration-tests/apps/helidon-quickstart-se/target' is experimental and must be enabled via '-H:+UnlockExperimentalVMOptions' in the future.
[INFO] Warning: The option '-H:IncludeResources=application.yaml|META-INF/native-image/reflect-config.json|logging.properties' is experimental and must be enabled via '-H:+UnlockExperimentalVMOptions' in the future.
[INFO] Warning: The option '-H:ReflectionConfigurationResources=META-INF/native-image/io.netty/transport/reflection-config.json' is experimental and must be enabled via '-H:+UnlockExperimentalVMOptions' in the future.
[INFO] Warning: The option '-H:Name=helidon-quickstart-se' is experimental and must be enabled via '-H:+UnlockExperimentalVMOptions' in the future. ==> expected: <true> but was: <false>
        at org.graalvm.tests.integration.RuntimesSmokeTest.testRuntime(RuntimesSmokeTest.java:166)
        at org.graalvm.tests.integration.RuntimesSmokeTest.helidonQuickStart(RuntimesSmokeTest.java:227)
```

**Comment by jerboaa** [comment]
All the integration test is doing is invoking `mvn package`. The rest is driven by the helidon-maven-plugin. We might need to remove/disable helidon when 24.0 comes out and blocks experimental flags use without unlock.
