### ISSUE TITLE
[23.1] jfrPerfTest fails with experimental VM warning

### ISSUE THREAD

**Issue by jerboaa** [Karm/mandrel-integration-tests#201]
The test fails with:

```
 Error:  Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1,247.701 s <<< FAILURE! - in org.graalvm.tests.integration.JFRTest
Error:  jfrPerfTest{TestInfo}  Time elapsed: 988.065 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: 
build-and-run.log log should not contain error or warning lines that are not whitelisted. See /home/runner/work/mandrel/mandrel/mandrel-integration-tests/testsuite/target/archived-logs/org.graalvm.tests.integration.JFRTest/jfrPerfTest/build-and-run.log and check these offending lines: 
Warning: The option '-H:+SignalHandlerBasedExecutionSampler' is experimental and must be enabled via '-H:+UnlockExperimentalVMOptions' in the future.
Warning: The option '-H:ReflectionConfigurationResources=META-INF/native-image/io.netty/netty-transport/reflection-config.json' is experimental and must be enabled via '-H:+UnlockExperimentalVMOptions' in the future.
Warning: Please re-evaluate whether any experimental option is required, and either remove or unlock it. The build output lists all active experimental options, including where they come from and possible alternatives. If you think an experimental option should be considered as stable, please file an issue. ==> expected: <true> but was: <false>
	at org.graalvm.tests.integration.JFRTest.jfrPerfTestRun(JFRTest.java:210)
	at org.graalvm.tests.integration.JFRTest.jfrPerfTest(JFRTest.java:176)
```

The `-H:+SignalHandlerBasedExecutionSampler` needs to get unlocked. netty issue is https://github.com/netty/netty/pull/13596

**Comment by jerboaa** [comment]
Re-opening as we still need to deal with:

```
Warning: The option '-H:ReflectionConfigurationResources=META-INF/native-image/io.netty/netty-transport/reflection-config.json' is experimental and must be enabled via '-H:+UnlockExperimentalVMOptions' in the future.
```

**Comment by zakkak** [comment]
> Re-opening as we still need to deal with:
> 
> ```
> Warning: The option '-H:ReflectionConfigurationResources=META-INF/native-image/io.netty/netty-transport/reflection-config.json' is experimental and must be enabled via '-H:+UnlockExperimentalVMOptions' in the future.
> ```

Dealt with in https://github.com/Karm/mandrel-integration-tests/pull/203
