### ISSUE TITLE
quarkus-full-microprofile test fails with lastest quarkus main (3.8-dev?)

### ISSUE THREAD

**Issue by jerboaa** [Karm/mandrel-integration-tests#245]
We see CI failures failing to build the quarkus-full-microprofile application:

```
Error:  Failed to execute goal on project quarkus-full-microprofile: Could not resolve dependencies for project org.graalvm.tests.integration:quarkus-full-microprofile:jar:1.0.0-SNAPSHOT: Could not find artifact io.quarkus:quarkus-rest-client:jar:999-SNAPSHOT -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
Error:  Tests run: 2, Failures: 0, Errors: 1, Skipped: 1, Time elapsed: 7.13 s <<< FAILURE! - in org.graalvm.tests.integration.RuntimesSmokeTest
Error:  quarkusFullMicroProfile{TestInfo}  Time elapsed: 7.13 s  <<< ERROR!
java.lang.IllegalArgumentException: Path to D:\a\mandrel\mandrel\apps\quarkus-full-microprofile\targetmust exist and regexp must nut be null.
	at org.graalvm.tests.integration.RuntimesSmokeTest.testRuntime(RuntimesSmokeTest.java:99)
	at org.graalvm.tests.integration.RuntimesSmokeTest.quarkusFullMicroProfile(RuntimesSmokeTest.java:202)
```

Seems to be caused by this:

```
Could not find artifact io.quarkus:quarkus-rest-client:jar:999-SNAPSHOT
```

CI run where we see this:
https://github.com/graalvm/mandrel/actions/runs/7545667449/job/20542614308#step:10:7593

**Comment by Karm** [comment]
@jerboaa  needs renaming from io.quarkus:quarkus-rest-client to io.quarkus:quarkus-resteasy-client
I'll have it fixed tomorrow.  
mere editting the .patch file now would break older Q 3
