### ISSUE TITLE
Warning logs: Unrecognized configuration key "quarkus.otel.traces.eusp.enabled" with latest quarkus main

### ISSUE THREAD

**Issue by jerboaa** [Karm/mandrel-integration-tests#252]
In most recent runs with the quarkus main branch we get the following warning logs when running the microprofile quarkus app:

```
Warning:  [io.quarkus.config] Unrecognized configuration key "quarkus.otel.traces.eusp.enabled" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
```

This then makes the Mandrel IT tests fail for `debugSymbolsQuarkus` and `quarkusFullMicroProfile` like so:

```
Warning: 6 01:40:24.188 INFO  [o.g.t.i.u.Logs] (checkLog) build-and-run.log log for quarkusFullMicroProfile contains whitelisted error: `[WARNING] [io.quarkus.deployment.configuration] Configuration property 'quarkus.package.type' has been deprecated and replaced by: [quarkus.package.jar.enabled, quarkus.package.jar.type, quarkus.native.enabled, quarkus.native.sources-only]'
2024-03-26 01:40:24.190 INFO  [o.g.t.i.u.Logs] (checkLog) build-and-run.log log for quarkusFullMicroProfile contains whitelisted error: `2024-03-26 01:40:24,179 SEVERE [io.qua.ope.run.exp.otl.VertxGrpcExporter] (vert.x-eventloop-thread-2) Failed to export spans. The request could not be executed. Full error message: Connection refused: localhost/127.0.0.1:4317 [Error Occurred After Shutdown]'
Error:  Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 296.871 s <<< FAILURE! - in org.graalvm.tests.integration.RuntimesSmokeTest
Error:  quarkusFullMicroProfile{TestInfo}  Time elapsed: 195.161 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: 
build-and-run.log log should not contain error or warning lines that are not whitelisted. See /home/runner/work/mandrel/mandrel/mandrel-integration-tests/testsuite/target/archived-logs/org.graalvm.tests.integration.RuntimesSmokeTest/quarkusFullMicroProfile/build-and-run.log and check these offending lines: 
Warning:  [io.quarkus.config] Unrecognized configuration key "quarkus.otel.traces.eusp.enabled" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
01:37:31,266 WARN  [io.qua.config] Unrecognized configuration key "quarkus.otel.traces.eusp.enabled" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo ==> expected: <true> but was: <false>
	at org.graalvm.tests.integration.RuntimesSmokeTest.testRuntime(RuntimesSmokeTest.java:158)
	at org.graalvm.tests.integration.RuntimesSmokeTest.quarkusFullMicroProfile(RuntimesSmokeTest.java:204)

[INFO] 
[INFO] Results:
[INFO] 
Error:  Failures: 
Error:    DebugSymbolsTest.debugSymbolsQuarkus:308 build-and-run.log log should not contain error or warning lines that are not whitelisted. See /home/runner/work/mandrel/mandrel/mandrel-integration-tests/testsuite/target/archived-logs/org.graalvm.tests.integration.DebugSymbolsTest/debugSymbolsQuarkus/build-and-run.log and check these offending lines: 
Warning:  [io.quarkus.config] Unrecognized configuration key "quarkus.otel.traces.eusp.enabled" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
01:13:20,206 WARN  [io.qua.config] Unrecognized configuration key "quarkus.otel.traces.eusp.enabled" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo ==> expected: <true> but was: <false>
Error:    RuntimesSmokeTest.quarkusFullMicroProfile:204->testRuntime:158 build-and-run.log log should not contain error or warning lines that are not whitelisted. See /home/runner/work/mandrel/mandrel/mandrel-integration-tests/testsuite/target/archived-logs/org.graalvm.tests.integration.RuntimesSmokeTest/quarkusFullMicroProfile/build-and-run.log and check these offending lines: 
Warning:  [io.quarkus.config] Unrecognized configuration key "quarkus.otel.traces.eusp.enabled" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
01:37:31,266 WARN  [io.qua.config] Unrecognized configuration key "quarkus.otel.traces.eusp.enabled" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo ==> expected: <true> but was: <false>
[INFO] 
Error:  Tests run: 19, Failures: 2, Errors: 0, Skipped: 5
```

**Comment by jerboaa** [comment]
This is a regression introduced with #251.
