### ISSUE TITLE
AWT JDK vs. native differs in hashsums in CI

### ISSUE THREAD

**Issue by Karm** [Karm/mandrel-integration-tests#283]
e.g.  
```
org.opentest4j.AssertionFailedError: 
There were errors checking the generated image files, see:
mytest.jpg's sha256 hash was 558234ef04d609d2187845b969baad779f55b69ab619b05c63226c3cb60293ba, expected hash: 1c04f261d4bcb7abdd86a519c38af4ef04cd01108b25734727df587f04c2f395
mytest.bmp's sha256 hash was 017337aa83b7ab4d123e2f24c27eb745ef77c26670f9234bdd3e4cf5851d893f, expected hash: d51df32a6064cda07aa968999c576f7b0f27d5777ae45f3719a8b27bee914044
mytest.gif's sha256 hash was 818bb1a5299c5b4a496e62a58335b57117a22b24e0107a98c0213b7e177f52e9, expected hash: b71c2a9e935558110b09fe72489e07603c2b07efeb31cdfa6d071e603d50ac6b
mytest.svg's sha256 hash was b7ac0dea3a2f6b282242c42e7f0f7bde54ea662307903a87d7c35aa69b62ea28, expected hash: a560cea4e7e564a206de9a91ffe7ebe42d866d3b3787f40f72271f485fad44c0
mytest.png's sha256 hash was 7d166e731cfc3b256f1fe7e2252b4c7844269e8a9726ef39e837d89a895f3e7e, expected hash: 460d3d05a4f504bbd2dd32f19700f27d68322d759764b9ffbbd9802ec6584588
mytest.tiff's sha256 hash was 7ab14578b481c35747b370e1ec92e5859dd87416e82750f0182f7153d81faa1d, expected hash: dcb95bf9e247947934847920c8a010a8c3fc6fb70309b15c9d3d1d0052d21106
mytest.wbmp's sha256 hash was a40d12407cc153d55cdcc3e412ab13d212cd490c1e5973d615a51c65d65c1f1a, expected hash: 75bb4346ac92f4dfd90c4a4cf26c92a591c89fd7fb2499d468934f784c3f6756 ==> expected: <true> but was: <false>
	at org.graalvm.tests.integration.AppReproducersTest.imageioAWT(AppReproducersTest.java:609)
	at org.graalvm.tests.integration.AppReproducersTest.imageioAWTTest(AppReproducersTest.java:502)
```

I can't reproduce it locally, so I am afraid the CI might get polluted `java` command? Does not happen on GHA, happens on Jenkins and not on all executors?

**Comment by Karm** [comment]
This will be fixed by #313
