### ISSUE TITLE
[24.1] Mandrel for JDK 23 nightly fails microprofile test

### ISSUE THREAD

**Issue by jerboaa** [Karm/mandrel-integration-tests#292]
In one of our nightly runs for Mandrel for JDK 23 we see this new failure:

```
Error:  Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 295.745 s <<< FAILURE! - in org.graalvm.tests.integration.RuntimesSmokeTest
Error:  quarkusFullMicroProfile{TestInfo}  Time elapsed: 185.388 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: 
build-and-run.log log should not contain error or warning lines that are not whitelisted. See /home/runner/work/mandrel/mandrel/mandrel-integration-tests/testsuite/target/archived-logs/org.graalvm.tests.integration.RuntimesSmokeTest/quarkusFullMicroProfile/build-and-run.log and check these offending lines: 
		at io.smallrye.mutiny.subscription.MultiSubscriber.onError(MultiSubscriber.java:73) ==> expected: <true> but was: <false>
	at org.graalvm.tests.integration.RuntimesSmokeTest.testRuntime(RuntimesSmokeTest.java:155)
	at org.graalvm.tests.integration.RuntimesSmokeTest.quarkusFullMicroProfile(RuntimesSmokeTest.java:199)

[INFO] 
```

See: https://github.com/graalvm/mandrel/actions/runs/11412917807/job/31760263362#step:11:21392

**Comment by zakkak** [comment]
This is tracked in https://github.com/Karm/mandrel-integration-tests/issues/290 closing as duplicate

**Comment by jerboaa** [comment]
OK, thanks. This wasn't obvious. I'll add a comment on #290.
